name: PlatformIO CI

on:
  push:
    branches:
      - 'dev/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Build firmware
      working-directory: software/o_c_REV/
      run: pio run -e oc_prod

    - name: Build flipped firmware
      working-directory: software/o_c_REV/
      run: pio run -e oc_prod_180

    - name: Copy artifact
      uses: actions/upload-artifact@v2
      with:
        name: o_C-${{github.sha}}
        path: software/o_c_REV/.pio/build/*/*.hex
